# Generated by Django 4.2.23 on 2025-08-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAdmin',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expense')),
            ],
            bases=('main.expense',),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount spent', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total monthly income', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.CharField(blank=True, help_text='Optional tags (comma-separated)', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel'), ('HEALTH', 'Health'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='No decription!', help_text='Description of the expense', max_length=200),
        ),
    ]
