# Generated by Django 4.2.23 on 2025-08-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expenseadmin_remove_expense_added_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseView',
        ),
    ]
