# Generated by Django 4.2.23 on 2025-08-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_expenseview'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
