# Generated by Django 4.2.23 on 2025-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expense_remaining_alter_expense_amount_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tags',
        ),
    ]
