# Generated by Django 4.2.23 on 2025-08-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usersalary_remove_expense_remaining_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order_num',)},
        ),
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='used_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
