# Generated by Django 4.2.23 on 2025-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options_category_order_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='name',
            field=models.CharField(default='My Salary', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.usersalary'),
        ),
    ]
