# Generated by Django 4.2.23 on 2025-08-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options_category_order_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='category',
            name='used_times',
        ),
    ]
