# Generated by Django 4.2.23 on 2025-08-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options_category_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalary',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
