# Generated by Django 4.2.23 on 2025-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options_alter_expense_amount_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='remaining_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
