# Generated by Django 4.2.23 on 2025-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usersalary_remaining_salary'),
    ]

    operations = [
    ]

migrations.AddField(
    model_name='usersalary',
    name='remaining_salary',
    field=models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True),
)