# Generated by Django 4.2.23 on 2025-08-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usersalary_name_alter_expense_amount_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersalary',
            name='name',
        ),
    ]
