# Generated by Django 4.2.23 on 2025-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250818_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashback_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cashback percent (0-100)', max_digits=5),
        ),
    ]
